import { Briefcase, Building2, Cog, Contact, DollarSign, GraduationCap, Layers, LifeBuoy, Map, MonitorSmartphone, Network, Rocket, Wrench } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type ServiceModule = { id: string; title: string; outcome: string; tools: string[]; labels: string[]; pain: string; solution: string; outcomes: string[]; ctaLabel: string; ctaHref: string };
export type SystemModule = { id: string; title: string; description: string; icon: LucideIcon; accent: 'cyan'|'blue'|'violet'; position:{x:number;y:number}; previewBullets:string[]; ctaLabel:string; ctaHref:string; children?:ServiceModule[] };

export const serviceModules: ServiceModule[] = [
{ id:'lead-capture', title:'Lead Capture Engine', outcome:'Turn enquiries into tracked opportunities.', tools:['Website','Forms','Email','WhatsApp','Sheets'], labels:['Captured','Qualified','Assigned','Reminded'], pain:'Leads arrive from multiple channels and go cold before someone responds.', solution:'Rapid Rise AI captures enquiries, qualifies intent, and routes every lead into one clear pipeline.', outcomes:['Instant lead acknowledgement','Clear owner assignment','No dropped enquiries','Trackable follow-up rhythm'], ctaLabel:'Request a lead system quote', ctaHref:'/quote' },
{ id:'workflow-automation', title:'Workflow Automation', outcome:'Remove repetitive admin between tools.', tools:['Zapier','Make','n8n','Apps Script','APIs'], labels:['Sync','Route','Notify','Update'], pain:'Your team repeats the same admin across tools every day.', solution:'Rapid Rise AI connects your stack and moves data to the right place automatically.', outcomes:['Less copy-paste work','Faster handovers','Cleaner reporting','Fewer missed tasks'], ctaLabel:'Request an automation quote', ctaHref:'/quote' },
{ id:'google-workspace', title:'Smart Google Workspace', outcome:'Make your current tools work together.', tools:['Gmail','Sheets','Drive','Calendar','Docs'], labels:['Label','Store','Remind','Report'], pain:'Important work gets buried in inboxes, sheets, and folders.', solution:'Rapid Rise AI structures Workspace workflows with automation, reminders, and live reporting.', outcomes:['Faster internal coordination','Consistent file trails','Shared operational visibility'], ctaLabel:'Explore Workspace systems', ctaHref:'/solutions/google-workspace' },
{ id:'internal-tools', title:'Web Apps and Internal Tools', outcome:'Build the screens your team actually needs.', tools:['Next.js','Supabase','Vercel','Auth','Dashboards'], labels:['Admin','Team','Client','Report'], pain:'Teams depend on scattered spreadsheets and chat updates to run operations.', solution:'Rapid Rise AI builds tailored internal apps, dashboards, and portals for daily workflows.', outcomes:['Centralized operations view','Reduced coordination overhead','Higher delivery consistency'], ctaLabel:'Request an internal tool quote', ctaHref:'/solutions/web-apps' },
{ id:'websites', title:'Websites that Convert', outcome:'Turn visitors into clear next actions.', tools:['SEO','Forms','CTA','Speed','Mobile'], labels:['Trust','CTA','Form','Follow-up'], pain:'Traffic arrives, but visitors leave without taking action.', solution:'Rapid Rise AI designs fast, conversion-focused websites with clear journeys and integrated follow-up.', outcomes:['Higher conversion quality','Clearer messaging','Better mobile performance'], ctaLabel:'Request a website quote', ctaHref:'/solutions/websites' },
{ id:'training', title:'Training and Enablement', outcome:'Help your team use modern tools properly.', tools:['Templates','SOPs','Classes','Coaching','Handover'], labels:['Learn','Adopt','Repeat','Improve'], pain:'Great systems fail when teams are not confident using them.', solution:'Rapid Rise AI provides practical training, templates, and coaching to drive adoption.', outcomes:['Faster onboarding','Higher tool adoption','Sustainable execution habits'], ctaLabel:'Explore training', ctaHref:'/solutions/training' },
{ id:'support-assistant', title:'Support Assistant', outcome:'Answer faster and hand off cleaner.', tools:['Chat','FAQ','Routing','Handoff','Inbox'], labels:['Reply','Summarize','Route','Handoff'], pain:'Customer messages wait too long and context is lost during handoff.', solution:'Rapid Rise AI configures assistants that answer quickly and route conversations with context.', outcomes:['Faster first responses','Cleaner escalations','Improved support consistency'], ctaLabel:'Build a support assistant', ctaHref:'/contact' },
];

export const systemModules: SystemModule[] = [
{ id:'services', title:'Services', description:'Core offerings and strategic systems.', icon:Layers, accent:'cyan', position:{x:16,y:18}, previewBullets:['Automation systems','Internal tools','Websites and training'], ctaLabel:'Explore Services', ctaHref:'/solutions', children:serviceModules },
{ id:'work', title:'Work', description:'Real results for real businesses.', icon:Briefcase, accent:'blue', position:{x:72,y:14}, previewBullets:['Case studies','Recent builds','Proof of outcomes'], ctaLabel:'View Work', ctaHref:'/work' },
{ id:'automation', title:'Automation', description:'Remove manual workflow overhead.', icon:Cog, accent:'cyan', position:{x:78,y:40}, previewBullets:['Routing and syncing','Follow-up systems','Ops automation'], ctaLabel:'Start automation audit', ctaHref:'/solutions/workflow-automation' },
{ id:'websites', title:'Websites', description:'High-converting websites that perform.', icon:MonitorSmartphone, accent:'blue', position:{x:65,y:68}, previewBullets:['Conversion-first UX','Fast mobile performance','Integrated lead forms'], ctaLabel:'Explore websites', ctaHref:'/solutions/websites' },
{ id:'internal-tools', title:'Internal Tools', description:'Custom portals, dashboards, and tooling.', icon:Wrench, accent:'violet', position:{x:38,y:76}, previewBullets:['Ops dashboards','Role-based access','Workflow portals'], ctaLabel:'Explore tools', ctaHref:'/solutions/web-apps' },
{ id:'google-workspace', title:'Google Workspace', description:'Connect Gmail, Sheets, Drive, and Docs.', icon:Building2, accent:'cyan', position:{x:14,y:58}, previewBullets:['Workspace automation','Smarter reporting','Cleaner handover'], ctaLabel:'Explore Workspace', ctaHref:'/solutions/google-workspace' },
{ id:'solutions', title:'Solutions', description:'Complete systems by business need.', icon:Network, accent:'blue', position:{x:50,y:10}, previewBullets:['Lead capture','Automation','Dashboards'], ctaLabel:'View Solutions', ctaHref:'/solutions' },
{ id:'pricing', title:'Pricing', description:'Flexible build scopes for your stage.', icon:DollarSign, accent:'violet', position:{x:88,y:58}, previewBullets:['Quick wins','Core systems','Ongoing support'], ctaLabel:'View pricing', ctaHref:'/pricing' },
{ id:'education', title:'Education', description:'Teach teams to use modern tools.', icon:GraduationCap, accent:'blue', position:{x:24,y:84}, previewBullets:['AI for work','Team enablement','Practical templates'], ctaLabel:'Explore education', ctaHref:'/education' },
{ id:'process', title:'Process', description:'How systems are diagnosed and shipped.', icon:Map, accent:'cyan', position:{x:54,y:86}, previewBullets:['Discovery','Build + QA','Training + handover'], ctaLabel:'See process', ctaHref:'/about' },
{ id:'contact', title:'Contact', description:'Start with a focused quote request.', icon:Contact, accent:'violet', position:{x:86,y:82}, previewBullets:['Request a quote','Book discovery','Get implementation plan'], ctaLabel:'Request a quote', ctaHref:'/quote' },
{ id:'support-assistant', title:'Support Assistant', description:'Faster replies and cleaner handoff.', icon:LifeBuoy, accent:'cyan', position:{x:8,y:36}, previewBullets:['AI-assisted responses','Intent routing','Escalation summaries'], ctaLabel:'Explore support', ctaHref:'/contact' },
{ id:'dashboards', title:'Dashboards', description:'Live business visibility and reporting.', icon:Rocket, accent:'blue', position:{x:47,y:56}, previewBullets:['Performance tracking','Bottleneck alerts','Executive oversight'], ctaLabel:'Build a dashboard', ctaHref:'/solutions/web-apps' },
];
