import { Bot, Briefcase, Building2, Cog, Contact, DollarSign, GraduationCap, Layers, Map, MonitorSmartphone, Network, Rocket, Wrench } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type ModuleDetail = { pain: string; solution: string; outcomes: string[]; tools: string[]; ctaLabel: string; ctaHref: string };
export type ServiceModule = { id: string; title: string; outcome: string; tools: string[]; labels: string[]; pain: string; solution: string; outcomes: string[]; ctaLabel: string; ctaHref: string };
export type SystemModule = { id: string; title: string; description: string; icon: LucideIcon; accent: 'cyan' | 'blue' | 'violet'; position: { x: number; y: number }; size: 'large' | 'medium' | 'small'; previewBullets: string[]; detail: ModuleDetail; children?: ServiceModule[] };

export const serviceModules: ServiceModule[] = [
  { id: 'lead-capture', title: 'Lead Capture Engine', outcome: 'Turn enquiries into tracked opportunities.', tools: ['Website', 'Forms', 'Email', 'WhatsApp', 'Sheets'], labels: ['Captured', 'Qualified', 'Assigned', 'Reminded'], pain: 'Leads arrive from multiple channels and go cold before someone responds.', solution: 'Rapid Rise AI captures enquiries, qualifies intent, and routes every lead into one clear pipeline.', outcomes: ['Instant lead acknowledgement', 'Clear owner assignment', 'No dropped enquiries', 'Trackable follow-up rhythm'], ctaLabel: 'Request a lead system quote', ctaHref: '/quote' },
  { id: 'workflow-automation', title: 'Workflow Automation', outcome: 'Remove repetitive admin between tools.', tools: ['Zapier', 'Make', 'n8n', 'Apps Script', 'APIs'], labels: ['Sync', 'Route', 'Notify', 'Update'], pain: 'Your team repeats the same admin across tools every day.', solution: 'Rapid Rise AI connects your stack and moves data to the right place automatically.', outcomes: ['Less copy-paste work', 'Faster handovers', 'Cleaner reporting', 'Fewer missed tasks'], ctaLabel: 'Request an automation quote', ctaHref: '/quote' },
  { id: 'google-workspace', title: 'Smart Google Workspace', outcome: 'Make your current tools work together.', tools: ['Gmail', 'Sheets', 'Drive', 'Calendar', 'Docs'], labels: ['Label', 'Store', 'Remind', 'Report'], pain: 'Important work gets buried in inboxes, sheets, and folders.', solution: 'Rapid Rise AI structures Workspace workflows with automation, reminders, and live reporting.', outcomes: ['Faster internal coordination', 'Consistent file trails', 'Shared operational visibility'], ctaLabel: 'Explore Workspace systems', ctaHref: '/solutions/google-workspace' },
  { id: 'internal-tools', title: 'Web Apps and Internal Tools', outcome: 'Build the screens your team actually needs.', tools: ['Next.js', 'Supabase', 'Vercel', 'Auth', 'Dashboards'], labels: ['Admin', 'Team', 'Client', 'Report'], pain: 'Teams depend on scattered spreadsheets and chat updates to run operations.', solution: 'Rapid Rise AI builds tailored internal apps, dashboards, and portals for daily workflows.', outcomes: ['Centralized operations view', 'Reduced coordination overhead', 'Higher delivery consistency'], ctaLabel: 'Request an internal tool quote', ctaHref: '/solutions/web-apps' },
  { id: 'websites', title: 'Websites that Convert', outcome: 'Turn visitors into clear next actions.', tools: ['SEO', 'Forms', 'CTA', 'Speed', 'Mobile'], labels: ['Trust', 'CTA', 'Form', 'Follow-up'], pain: 'Traffic arrives, but visitors leave without taking action.', solution: 'Rapid Rise AI designs fast, conversion-focused websites with clear journeys and integrated follow-up.', outcomes: ['Higher conversion quality', 'Clearer messaging', 'Better mobile performance'], ctaLabel: 'Request a website quote', ctaHref: '/solutions/websites' },
  { id: 'training', title: 'Training and Enablement', outcome: 'Help your team use modern tools properly.', tools: ['Templates', 'SOPs', 'Classes', 'Coaching', 'Handover'], labels: ['Learn', 'Adopt', 'Repeat', 'Improve'], pain: 'Great systems fail when teams are not confident using them.', solution: 'Rapid Rise AI provides practical training, templates, and coaching to drive adoption.', outcomes: ['Faster onboarding', 'Higher tool adoption', 'Sustainable execution habits'], ctaLabel: 'Explore training', ctaHref: '/solutions/training' },
  { id: 'support-assistant', title: 'Support Assistant', outcome: 'Answer faster and hand off cleaner.', tools: ['Chat', 'FAQ', 'Routing', 'Handoff', 'Inbox'], labels: ['Reply', 'Summarize', 'Route', 'Handoff'], pain: 'Customer messages wait too long and context is lost during handoff.', solution: 'Rapid Rise AI configures assistants that answer quickly and route conversations with context.', outcomes: ['Faster first responses', 'Cleaner escalations', 'Improved support consistency'], ctaLabel: 'Build a support assistant', ctaHref: '/contact' },
];

const detail = (ctaLabel: string, ctaHref: string, pain: string, solution: string, outcomes: string[], tools: string[]): ModuleDetail => ({ ctaLabel, ctaHref, pain, solution, outcomes, tools });

export const systemModules: SystemModule[] = [
  { id: 'services', title: 'Services', description: 'Core offerings and strategic systems.', icon: Layers, accent: 'cyan', position: { x: 50, y: 62 }, size: 'large', previewBullets: ['Lead capture + follow-up systems', 'Automation, portals, and dashboards', 'Training + support enablement'], detail: detail('Explore all services', '/solutions', 'Teams run disconnected systems that create handoff friction.', 'We design one operational layer across acquisition, operations, and reporting.', ['Consolidated delivery stack', 'Cleaner team coordination', 'Faster customer response times'], ['Automation systems', 'Web apps', 'Dashboards', 'Training']), children: serviceModules },
  { id: 'solutions', title: 'Solutions', description: 'Complete systems by business need.', icon: Network, accent: 'blue', position: { x: 41, y: 24 }, size: 'medium', previewBullets: ['Lead capture solutions', 'Workflow automation stacks', 'Workspace + operations systems'], detail: detail('View solution pages', '/solutions', 'Businesses know the pain but not the right system architecture.', 'Rapid Rise AI bundles tooling, workflows, and UI into outcome-driven solutions.', ['Faster implementation scope', 'Clear build priorities', 'Lower integration risk'], ['Solution architecture', 'Delivery plans', 'Tooling stacks']) },
  { id: 'work', title: 'Work', description: 'Real results for real businesses.', icon: Briefcase, accent: 'violet', position: { x: 35, y: 79 }, size: 'small', previewBullets: ['Delivery proof and rollout quality', 'System examples and outcomes', 'Real execution snapshots'], detail: detail('View work examples', '/work', 'It is hard to trust automation vendors without execution proof.', 'We show build quality, operational outcomes, and production examples.', ['Improved buyer confidence', 'Clear implementation expectations', 'Transparent delivery standards'], ['Case studies', 'Deployment captures', 'Handover packs']) },
  { id: 'pricing', title: 'Pricing', description: 'Flexible build scopes for your stage.', icon: DollarSign, accent: 'blue', position: { x: 50, y: 84 }, size: 'small', previewBullets: ['Quick wins and scoped modules', 'Core stack and expansion plans', 'Budget-aware implementation'], detail: detail('Review pricing options', '/pricing', 'Teams delay improvements because pricing is unclear.', 'Rapid Rise AI provides phased options based on current business stage.', ['Predictable delivery scope', 'Faster internal approvals', 'Clear upgrade path'], ['Scoping', 'Phased rollouts', 'Support options']) },
  { id: 'education', title: 'Education', description: 'Teach teams to use modern tools.', icon: GraduationCap, accent: 'violet', position: { x: 64, y: 79 }, size: 'small', previewBullets: ['AI for work training', 'Operational playbooks', 'Adoption and enablement'], detail: detail('Explore education', '/education', 'Good systems fail when teams never adopt them.', 'We provide practical training and handover programs for teams.', ['Stronger adoption', 'Faster onboarding', 'Higher confidence in daily use'], ['Classes', 'SOPs', 'Template kits']) },
  { id: 'process', title: 'Process', description: 'How systems are diagnosed and shipped.', icon: Map, accent: 'cyan', position: { x: 50, y: 43 }, size: 'small', previewBullets: ['Discover bottlenecks first', 'Build with QA and validation', 'Launch with support and handover'], detail: detail('See how we deliver', '/about', 'Most projects fail from vague requirements and weak QA.', 'Rapid Rise AI follows a structured discovery-to-handover workflow.', ['Lower delivery risk', 'Clear acceptance criteria', 'Reliable launch quality'], ['Discovery', 'Build QA', 'Launch training']) },
  { id: 'contact', title: 'Contact', description: 'Start with a focused quote request.', icon: Contact, accent: 'blue', position: { x: 78, y: 55 }, size: 'small', previewBullets: ['Request quote or audit', 'Share systems context', 'Get a practical next-step plan'], detail: detail('Request a quote', '/quote', 'Businesses often waste time in discovery calls without clarity.', 'Use a focused request flow so we can scope the right system quickly.', ['Faster project qualification', 'Clear scope direction', 'Actionable next steps'], ['Quote form', 'Requirements capture', 'Planning']) },
  { id: 'automation', title: 'Automation', description: 'Remove manual workflow overhead.', icon: Cog, accent: 'cyan', position: { x: 32, y: 40 }, size: 'medium', previewBullets: ['Routing and syncing rules', 'Automated status updates', 'Cross-tool task handoffs'], detail: detail('Explore automation', '/solutions/workflow-automation', 'Manual copy/paste work slows down every team.', 'We automate recurring workflows and route data where it belongs.', ['Reduced admin load', 'Fewer missed handoffs', 'Faster operational flow'], ['n8n', 'Zapier', 'Make', 'Apps Script']) },
  { id: 'websites', title: 'Websites', description: 'High-converting websites that perform.', icon: MonitorSmartphone, accent: 'blue', position: { x: 28, y: 66 }, size: 'medium', previewBullets: ['High-conversion structure', 'Integrated lead capture', 'Fast mobile performance'], detail: detail('Explore websites', '/solutions/websites', 'Many websites look polished but fail to convert interest into leads.', 'We build conversion-driven websites connected to your follow-up systems.', ['More qualified enquiries', 'Stronger CTA performance', 'Better mobile conversion'], ['Next.js', 'SEO', 'Form workflows']) },
  { id: 'internal-tools', title: 'Internal Tools', description: 'Custom portals, dashboards, and tooling.', icon: Wrench, accent: 'violet', position: { x: 69, y: 59 }, size: 'medium', previewBullets: ['Team and client portals', 'Ops screens for daily execution', 'Custom admin workflows'], detail: detail('Explore internal tools', '/solutions/web-apps', 'Teams rely on ad-hoc spreadsheets and chat updates to operate.', 'We build internal software that matches your real workflow.', ['Single source of truth', 'Faster operational execution', 'Improved accountability'], ['Next.js', 'Auth', 'Supabase', 'Dashboards']) },
  { id: 'google-workspace', title: 'Google Workspace', description: 'Connect Gmail, Sheets, Drive, Calendar, and Docs.', icon: Building2, accent: 'cyan', position: { x: 77, y: 34 }, size: 'small', previewBullets: ['Connected Workspace automation', 'Cross-app reminders + reporting', 'Improved team coordination'], detail: detail('Explore Workspace systems', '/solutions/google-workspace', 'Workspace tools are powerful but often remain disconnected.', 'We integrate Gmail, Sheets, Drive, and Calendar into one operating flow.', ['Less context switching', 'Consistent tracking', 'Clear reporting visibility'], ['Gmail', 'Sheets', 'Drive', 'Calendar', 'Docs']) },
  { id: 'dashboards', title: 'Dashboards', description: 'Live business visibility and reporting.', icon: Rocket, accent: 'blue', position: { x: 62, y: 24 }, size: 'small', previewBullets: ['Live KPI visibility', 'Workflow and SLA monitoring', 'Decision-ready reporting'], detail: detail('Build a dashboard', '/solutions/web-apps', 'Without reliable reporting, teams react too late.', 'We build dashboards that surface bottlenecks and key performance signals.', ['Faster insights', 'Early issue detection', 'Improved accountability'], ['Dashboards', 'Data pipelines', 'Alerting']) },
  { id: 'support-assistant', title: 'Support Assistant', description: 'Faster replies and cleaner handoff.', icon: Bot, accent: 'cyan', position: { x: 20, y: 52 }, size: 'small', previewBullets: ['AI-assisted first responses', 'Context-rich escalation routing', 'Summaries for human handoff'], detail: detail('Explore support systems', '/contact', 'Support inboxes become slow and inconsistent as demand grows.', 'We deploy assistants that answer quickly and route high-value cases correctly.', ['Faster first response', 'Consistent triage', 'Cleaner support handoff'], ['Chat flows', 'Knowledge routing', 'Inbox handoff']) },
];
