export const siteContent = {
  metadata: {
    siteName: 'Rapid Rise AI',
    baseUrl: 'https://rapidriseai.com',
    defaultOg: '/images/brand/og-image.svg',
  },
  nav: {
    items: [
      { label: 'Solutions', href: '/solutions' },
      { label: 'Work', href: '/work' },
      { label: 'Products and Pricing', href: '/products/pricing' },
      { label: 'Education', href: '/education' },
      { label: 'About', href: '/about' },
      { label: 'Contact', href: '/contact' },
    ],
  },
  trust: ['Response within 24 hours.', 'No spam. No pressure.', 'Clear scope, clean delivery.', 'Built around real workflows, not hype.'],
  footer: {
    company: 'Rapid Rise AI (Pty) Ltd', tagline: 'Business automation and software systems', email: 'team@rapidriseai.com', phone: '+27 64 903 1234', cipc: '2024/727338/07', vat: 'Not VAT registered',
    links: [{ label: 'Privacy Policy', href: '/privacy' }, { label: 'Terms', href: '/terms' }, { label: 'Cookie Policy', href: '/cookies' }],
  },
  home: {
    seo: { title: 'Rapid Rise AI | Business Automation and Software Systems', description: 'Manual work is draining your business. We build automation and software systems that cut admin, speed up responses, and stop things slipping through the cracks.' },
    hero: { h1: 'Manual work is draining your business.', sub: 'We build business automation and software systems that cut admin, speed up responses, and stop things slipping through the cracks.' },
  },
  solutionsHub: { seo: { title: 'Solutions | Rapid Rise AI', description: 'Explore Rapid Rise AI solutions: lead capture, workflow automation, smart Google Workspace, web apps, converting websites, and training.' } },
  solutionPages: {
    'lead-capture': { seo: { title: 'Lead Capture and Follow Up Systems | Rapid Rise AI', description: 'Stop losing enquiries. Capture requests properly, respond faster, and follow up consistently.' }, hero: { h1: 'Stop losing enquiries to slow follow-ups.', sub: 'We build lead capture and follow-up systems that respond faster, track everything, and keep your pipeline moving.' }, problems: ['Enquiries arrive across channels and get missed','Follow-ups depend on memory','Quotes take too long to send','No clear tracking or ownership','Leads go cold before you reply'], build: ['Quote request and enquiry flows (website and forms)','Lead tracking pipeline in Google Sheets or CRM','Automatic internal notifications','Follow-up reminders and escalation rules','Status tracking: New, Contacted, Qualified, Won, Lost','Clean handover documentation'], workflows: ['Website form to lead sheet to internal notify to follow-up reminders','Multiple inboxes to one pipeline to auto tagging and routing','Missed call or message to capture to create task to confirm next steps'], tools: ['Google Sheets and Apps Script','Email and WhatsApp workflows','Optional: Assistant layer for FAQ and triage when useful'], delivery: ['Quick Wins (2 weeks): basic capture plus tracking plus notifications','Core System (4 to 6 weeks): multi-channel capture plus routing plus follow-up logic plus dashboard','Scale and Support (monthly): ongoing improvements plus new flows'], faq: [{q:'Do you integrate with our existing inbox and WhatsApp?',a:'Yes. We design around your current process first.'},{q:'Can we start without automatic emails to customers?',a:'Yes. We can keep outbound email manual while still tracking everything.'},{q:'Will this work for any industry?',a:'Yes. The workflow stays the same, only the questions change.'}], cta:'Capture properly. Follow up consistently.' },
    'workflow-automation': { seo: { title: 'Workflow Automation and Integrations | Rapid Rise AI', description: 'Connect your tools and remove repetitive work with reliable automation and integrations.' }, hero:{h1:'If it is still manual, it is leaking time and money.',sub:'We connect your tools into workflows that reduce admin, prevent mistakes, and keep work moving automatically.'},problems:['Copy-paste between systems','Data is duplicated and inconsistent','Tasks fall through cracks during handoffs','No alerts or accountability','Reporting is slow and unreliable'],build:['Automations between tools using triggers and rules','Data sync, validation, and error handling','Approvals and routing workflows','Notifications and escalation logic','Activity logs and tracking','Clean documentation so your team can run it'],workflows:['Form submission to create row to create folder to notify owner','Invoice generated to update tracker to notify finance to schedule follow-up','Status change to alert team to create task list to update dashboard'],tools:['Make, Zapier, n8n (as required)','Webhooks and APIs','Google Workspace services','Optional: assistant layer for summarising requests and drafting replies'],delivery:['Quick Wins: 1 to 3 automations plus tracking','Core System: end-to-end integration pipeline','Scale: ongoing additions and reliability upgrades'],faq:[{q:'Can you automate across different software tools?',a:'Yes. That is the point.'},{q:'What about failures and edge cases?',a:'We build guardrails, logs, and alerts.'},{q:'Will staff still have control?',a:'Yes. Automations are designed with human checkpoints where needed.'}],cta:'Build the workflow once. Stop repeating the work.'},
    'google-workspace': { seo: { title: 'Smart Google Workspace Automation | Rapid Rise AI', description: 'Automate Sheets, Gmail, Drive, Calendar, and reporting with a smarter Google Workspace environment.' }, hero:{h1:'Turn Google Workspace into a system, not a mess.',sub:'We automate Google Sheets, Gmail, Drive, and Calendar so your team stops running the business from scattered files.'},problems:['Sheets used as databases with no structure','Manual updates and repeated admin','Files and folders not standardised','No approvals or tracking','Reporting takes too long'],build:['Automated Sheets pipelines (validated inputs, clean structure)','Apps Script automation for admin and workflows','Folder creation and document templates','Email automation for internal notifications','Calendar scheduling and reminders','Dashboards for tracking and reporting'],workflows:['New lead to create folder to generate docs to notify team','Quote request to validate to assign owner to update pipeline','Weekly reporting to auto compile to email summary to owners'],tools:['Google Sheets, Drive, Gmail, Calendar','Google Apps Script','Optional: assistant layer for summarising threads and drafting internal updates'],delivery:['Quick Wins: clean structure plus 1 key automation','Core System: full workspace workflow and reporting','Scale: improvements, maintenance, new modules'],faq:[{q:'Do we need a new CRM?',a:'Not necessarily. Often a smart workspace is enough.'},{q:'Can you secure access by roles?',a:'Yes. Permissions and roles are part of the build.'}],cta:'Make the workspace reliable.'},
    'web-apps': { seo: { title: 'Web Apps and Internal Tools | Rapid Rise AI', description: 'Build internal tools, dashboards, portals, and trackers that remove chaos and improve execution.' }, hero:{h1:'Stop managing the business in chats and spreadsheets alone.',sub:'We build lightweight web apps and internal tools that organise work, track progress, and simplify execution.'},problems:['Processes live in people’s heads','No clean system for tracking','Work is hard to hand over','Reporting is manual','Teams rely on admin to keep things moving'],build:['Internal dashboards and portals','Workflow trackers and status systems','Quote and booking tools','Simple CRM-style tools when needed','Admin interfaces built for speed and clarity'],workflows:['Internal portal to request intake to approvals to assigned tasks','Dashboard to live pipeline to owner and next step','Booking tool to schedule request to confirm to track'],tools:['Next.js and React','Google Sheets plus Apps Script as backend-lite','Optional database if required later'],delivery:['Quick Wins: MVP tool for one workflow','Core System: multi-module internal system','Scale: upgrades, refinements, new features'],faq:[{q:'Is this a full software rebuild?',a:'No. We build what you need to run better, not what looks fancy.'},{q:'Can it grow later?',a:'Yes. Built modular so proof and features can be added.'}],cta:'Build the tool your team actually uses.'},
    websites: { seo: { title: 'Websites that Convert | Rapid Rise AI', description: 'Premium websites built to capture leads, build trust, and drive enquiries without clutter.' }, hero:{h1:'A website should capture leads, not just look nice.',sub:'We build premium, fast websites that communicate value clearly and convert visitors into real enquiries.'},problems:['Visitors do not understand what you do','No clear CTA flow','Weak trust and proof','Slow pages, messy layout','Forms do not route correctly'],build:['Conversion-first structure and copy','Clear CTAs and lead capture flow','Trust elements and proof framework','Portfolio and case study system','Fast, mobile-first build','Easy content updates'],workflows:['Landing page to quote request to tracked lead','Service page to quick FAQ support widget to quote CTA','Work page to case study to conversion CTA'],tools:['Next.js and React','Cloudflare Pages hosting preferred','Optional assistant widget for FAQ and capture'],delivery:['Quick Wins: single high-converting landing page','Core System: full website plus work plus quote flow','Scale: ongoing SEO and conversion improvements'],faq:[],cta:'Make your site convert properly.'},
    training: { seo: { title: 'Training and Enablement | Rapid Rise AI', description: 'Practical training that helps your team work faster with modern tools and better workflows.' }, hero:{h1:'Train your team to work faster and smarter.',sub:'Practical training focused on real workflows, communication, and process improvement. No theory overload.'},problems:['Team is unsure what tools to use','Inconsistent output and quality','Time wasted on avoidable admin','Poor prompt use and unclear instructions','No standard operating process'],build:['Training sessions and playbooks','Templates for common work tasks','Workflow mapping and best practices','Optional assistant layer for common questions','Recordings and documentation'],workflows:['Modern admin and communication workflows','Document and inbox handling','Workflow thinking and automation readiness','Optional assistant usage when appropriate'],tools:[],delivery:[],faq:[],cta:'Better training. Better systems.'},
  },
};
