import {
  Bot,
  ChartNoAxesCombined,
  ClipboardCheck,
  FileText,
  Gauge,
  Globe,
  GraduationCap,
  Handshake,
  Headset,
  Inbox,
  LaptopMinimal,
  Lock,
  MousePointerClick,
  Quote,
  Route,
  ShieldCheck,
  Timer,
  Workflow,
} from 'lucide-react';

export const systemIcons = {
  leadCapture: MousePointerClick,
  inboxRouting: Inbox,
  automation: Workflow,
  dashboard: Gauge,
  portal: LaptopMinimal,
  quoteGenerator: Quote,
  supportAssistant: Bot,
  googleWorkspace: Route,
  website: Globe,
  training: GraduationCap,
  handover: Handshake,
  tracking: ChartNoAxesCombined,
  visibility: ClipboardCheck,
  security: Lock,
  responseTime: Timer,
  documentation: FileText,
  compliance: ShieldCheck,
  support: Headset,
};
